export const VALID_TAGS = [
  'CHANGED_MINDSET',
  'FINANCIAL_MINDSET',
  'EMOTIONAL_SKILLS',
  'PRACTICAL_BUSINESS',
  'PRODUCTIVITY',
  'ENRICHING_CONCEPTS',
  'EARN_MONEY',
  'RELAXING',
  'BOOSTS_CAPABILITIES',
  'IMPROVES_RELATIONSHIPS',
  'REREAD_WORTHY',
  'REFERENCE_BOOK',
  'INSPIRING',
  'IMPACTFUL',
  'REVEALING',
] as const;

export type BookTagKey = typeof VALID_TAGS[number];
